### ISSUE TITLE
autoplay prop doesnt work

### ISSUE THREAD

**Issue by hvardhan617** [benwiley4000/react-gif-player#26]
```jsx
<GifPlayer
  src={
    "https://raw.githubusercontent.com/benwiley4000/react-gif-player/master/flip_the_frog.gif"
  }
  still={
    "https://raw.githubusercontent.com/benwiley4000/react-gif-player/master/flip_the_frog.jpg"
  }
  autoplay="true"
/>
```

Autoplay isnt working

**Comment by benwiley4000** [comment]
Hey @hvardhan617, thanks for reporting your issue. I hope you don't mind I re-formatted your comment a bit so the code is easier to read.

It seems to me like it should work fine (you don't need `="true"` after autoplay since it's a boolean, not a string, so you could try changing it to just `autoplay`, but I don't think that's the problem).

Could you try reproducing your issue in this jsfiddle? https://jsfiddle.net/a18wo65s/1/

I added react-gif-player as a dependency already.

**Comment by benwiley4000** [comment]
@hvardhan617 any update?

**Comment by hvardhan617** [comment]
Hey @benwiley4000 .I have checked it yesterday..and this seems to be working now.Thanks
